spring:
  application:
    name: ${LOG_METADATA_SOURCE}
  kafka:
    bootstrap-servers:
    properties:
      application.id: local.sports.data.streams.consumer.java
      group_id: local.sports.data.streams.consumer.java
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config:
      schema.registry.url:

input:
  data:
    type:

avro:
  serdes:
    enabled:

client:
  name: